config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :recipefoods
  resources :foods
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/public_recipes', to: 'recipes#public'
  get '/shopping_list', to: 'shopping_list#shopping_list'

  # Defines the root path route ("/")
   root "welcome#index"
end

app/models/recipefood.rb
class Recipefood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/controllers/recipefoods_controller.rb
class RecipefoodsController < ApplicationController
  before_action :set_recipefood, only: %i[show edit update destroy]

  # GET /recipefoods or /recipefoods.json
  def index
    @recipefoods = Recipefood.all
  end

  # GET /recipefoods/1 or /recipefoods/1.json
  def show; end

  # GET /recipefoods/new
  def new
    @recipefood = Recipefood.new
    @foods = current_user.foods
    @food_items = []
    @foods.map do |food|
      @food_items << [food.name, food.id]
    end
    @recipe = current_user.recipes
    @recipe_items = []
    @recipe.map do |recipe|
      @recipe_items << [recipe.name, recipe.id]
    end
  end

  # GET /recipefoods/1/edit
  def edit; end

  # POST /recipefoods or /recipefoods.json
  def create
    @recipefood = Recipefood.new(recipefood_params)
    @recipe = current_user.recipes.find_by(id: params[:recipe_id])

    respond_to do |format|
      if @recipefood.save
        format.html { redirect_to recipefood_url(@recipefood), notice: 'Recipefood was successfully created.' }
        format.json { render :show, status: :created, location: @recipefood }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipefood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipefoods/1 or /recipefoods/1.json
  def update
    respond_to do |format|
      if @recipefood.update(recipefood_params)
        format.html { redirect_to recipefood_url(@recipefood), notice: 'Recipefood was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipefood }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipefood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipefoods/1 or /recipefoods/1.json
  def destroy
    @recipefood.destroy

    respond_to do |format|
      format.html { redirect_to recipefoods_url, notice: 'Recipefood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipefood
    @recipefood = Recipefood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipefood_params
    params.require(:recipefood).permit(:quantity, :food_id, :recipe_id)
  end
end

app/helpers/recipefoods_helper.rb
module RecipefoodsHelper
end

app/views/recipefoods/_form.html.erb
<%= form_with(model: recipefood) do |form| %>
  <% if recipefood.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipefood.errors.count, "error") %> prohibited this recipefood from being saved:</h2>

      <ul>
        <% recipefood.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container">
  <div class="form-group">
    <%= form.label :quantity %><br />
    <%= form.text_field :quantity, class:"form-control", placeholder: "Quantity" %>
  </div>

<%= form.label :Recipe, class: "form-input-label" %>
   <%= form.select :recipe_id, options_for_select(@recipe_items), {}, { :class => 'form-select mb-2' } %>


  <%= form.label :Food, class: "form-input-label" %>
   <%= form.select :food_id, options_for_select(@food_items), {}, { :class => 'form-select mb-2' } %>

  <div class="submit-button">
    <%= form.submit class: "btn btn-outline-dark btn-lg" %>
  </div>
</div>
<% end %>

app/views/recipefoods/index.html.erb
<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Quantity</th>
        <th scope="col">food_id</th>
        <th scope="col">recipe_id</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipefoods.each do |recipefood| %>
      <tr>
        <td><%= recipefood.quantity %></td>
        <td><%= recipefood.food.name %></td>
        <td><%= recipefood.recipe.name %></td>
        <td><%= link_to 'Modify', class: "btn btn-outline-danger" %><span><%= link_to 'Remove', class: "btn btn-outline-danger" %></span></td>
      </tr>
    </tbody>
    <%end%>
  </table>
</div>

app/views/recipefoods/new.html.erb
<h1 class="text-center">Add ingredients</h1>

<%= render "form", recipefood: @recipefood %>

<br>

<div>
  <%= link_to "Back to recipefoods", recipefoods_path %>
</div>