config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :recipefoods
  resources :foods
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/public_recipes', to: 'recipes#public'
  get '/shopping_list', to: 'shopping_list#shopping_list'

  # Defines the root path route ("/")
   root "welcome#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipefoods, dependent: :destroy
  has_many :foods, through: :recipefoods

  validates :name, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes.order(:id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        # format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = current_user.recipes.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public
    @public_recipies = Recipe.where(public: 'true')
    @user = current_user
    @recipe = Recipe.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: Recipe.new do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %> 
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time, class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time, class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description,  class:"form-control"  %>
  </div>

  <div >
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div class="submit-button">
    <%= form.submit "Create Recipe", class: "btn btn-outline-dark btn-lg " %>
  </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="card m-auto" style="width: 50rem;">
  <div class="card-body">
    <h5 class="card-title"><%= recipe.name %></h5>
    <p class="card-text"><%= recipe.description %></p>
    <p><%= button_to "Delete", recipe_path(recipe), class: 'btn', method: :delete %></p>
    <a href="#" class="btn "><%= link_to "Show this recipe", recipe %></a>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class = "text-center">Recipes</h1>
<span class="text-right mr-5" ><%= link_to "New recipe", new_recipe_path %></span>


<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="text-center">New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public.html.erb
<h1 class="text-center mt-4">Public Recipes</h1>
<div class="container">
  <% @public_recipies.includes(:user, :recipefoods).each do |recipe| %>
  <%if can? :read, recipe%>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          <h3 class="card-title text-success">Made By: <%= @user.name %></h3>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to recipe.name, recipe_path(recipe), class: "underline" %></h5>
          <div class="card-text"><%= simple_format(truncate(recipe.description, length:100)) %></div>
          <div class="card-text">
            <p>Total food items: <%=recipe.recipefoods.count%></p>
            <p>Total price:
              <%a = 0%>
              <% recipe.recipefoods.each do |recipefood| %>
              <% a += recipefood.food.price.to_int %>
              <%end%>
              <%= a%> $
            </p>
          </div>

          <%= link_to 'View', recipe_path(recipe), class: "btn btn-outline-success" %>
          <%if can? :destroy, recipe%>
          <%= link_to 'Remove', recipe_path(recipe), data: { turbo_method: 'delete', turbo_confirm: "Are you sure to delete" }, class: "btn btn-outline-danger" %>
          <%end%>
        </div>
        <div class="card-footer text-muted">
          <p> created <%= time_ago_in_words(recipe.created_at) %> ago, updated <%= time_ago_in_words(recipe.updated_at) %> ago </p>
        </div>
      </div>
    </div>
  </div>
  <%end%>
  <%end%>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>
<!-----------
<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %> |
  <%= link_to "Add ingredient", new_recipefood_path(@recipe) %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>
------------->



<!------------------------------------------------->
<h1 class="text-center mt-4 fst-italic"><%= @recipe.name.capitalize %></h1>
<div class="container">
  <h3 class="mt-2 text-left"> Preparation time: <%= @recipe.preparation_time %></h3>
  <h3 class="mt-2 text-right">Cooking time: <%= @recipe.cooking_time %></h3>
  <h3 class="mt-2">Details: <%= @recipe.description %></h3>
</div>

<div class="button-cont d-flex m-auto">
  <%= link_to "Generate Shopping list", shopping_list_path, class: "btn btn-outline-success " %>
  <%if can? :update, @recipe%>
  <%= link_to "Add ingredintes", new_recipefood_path, class: "btn btn-outline-primary " %>
  <%end%>
</div>
<hr class="line" />  
<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <%if can? :destroy, @recipe%>
        <th scope="col">Action</th>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipefoods.each do |recipefood| %>
      <tr>
        <td><%= recipefood.food.name.capitalize %></td>
        <td><%= recipefood.food.quantity %></td>
        <td><%= recipefood.food.price %></td>
        <%if can? :update, @recipe%>
        <td><%= link_to 'Modify', edit_food_path(recipefood.food) , class: "btn btn-outline-primary underline" %>
          <%end%>
          <%if can? :destroy, @recipe%>
          <span><%= link_to 'Remove', food_path(recipefood.food), data: { turbo_method: 'delete', turbo_confirm: "Are you sure to delete" }, class: "btn btn-outline-danger underline" %></span>
          <%end%>
        </td>
      </tr>
    </tbody>
    <%end%>
  </table>