config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :recipefoods
  resources :foods
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/public_recipes', to: 'recipes#public'
  get '/shopping_list', to: 'shopping_list#shopping_list'

  # Defines the root path route ("/")
   root "welcome#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipefoods, dependent: :destroy
  has_many :recipes, through: :recipefoods

  validates :name, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods.order(:id)
  end

  # GET /foods/1 or /foods/1.json
  def show
    @food = current_user.foods.find(params[:id])
  end

  # GET /foods/new
  def new
    @food = current_user.foods.build
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        # format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = current_user.foods.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
  <table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement</th>
      <th scope="col">Unit price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
<% @foods.includes(:user).each do |food| %>
  <tbody>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td><%= button_to "Delete", food_path(food), method: :delete %></td>
    </tr>
  </tbody>
<% end %>
</table>

app/views/foods/_form.html.erb
<%= form_with(model: @food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Foods</h1>

<p class = "text-right mr-5"><%= link_to "Add food", new_food_path %><p>

<div id="foods">
  
    <%= render "food" %>
  
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>