config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :recipefoods
  resources :foods
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/public_recipes', to: 'recipes#public'
  get '/shopping_list', to: 'shopping_list#shopping_list'

  # Defines the root path route ("/")
   root "welcome#index"
end

app/views/layouts/_navbar.html.erb
<div class="container_navbar">
    <span class="title">Y🍽️V🏠</span>
    <nav class="nav">
        
        <ul class="nav_list">
        <%if user_signed_in?%>
            <li><%= link_to "Home 🏠", root_path%></li>
            <li><%= link_to "Food 🍽️", foods_path%></li>
            <li><%= link_to "Recipe 🍜", recipes_path%></li>
            <li><%= link_to "List 🛒", shopping_list_path%></li>
            <li><%= link_to "Public Recipies 📢", public_recipes_path%></li>
            <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign_out" %></li>
            <%else%>
            <li><%= link_to "Sign In",  new_user_session_path %></li>
        <%end%>
        </ul>
        
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>